version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Upload to server
          command: node .circleci/deploy.js
      - run:
          name: Completed
          command: echo "Project built and deployed"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
