version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run:
                  name: Packages installation
                  command: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Project build
                  command: npm run build
            - run:
                  name: Server upload
                  command: node .circleci/deploy.js
            - run:
                  name: Completed
                  command: echo "Project built and deployed"

workflows:
    version: 2
    deploy:
        jobs:
            - build:
                  context: Max Altena websites
                  filters:
                      branches:
                          only:
                              - master
