name: 🦮 Reviewdog

on:
    pull_request:
        branches:
            - development
            - staging
            - production

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v2

      - name: 🎀 Lint files
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
